const players=[{id:'alice',seat:0,pseudo:'Alice',active:true,score:12,reserve:80,correct:3,incorrect:1,timeouts:0,averageLevel:4,lives:3,submitted:false},{id:'bob',seat:1,pseudo:'Baptiste',active:false,score:8,reserve:60,correct:2,incorrect:2,timeouts:0,averageLevel:4,lives:2,submitted:false}];
const common={stateSchemaVersion:1,mySeat:0,activeSeat:0,activePlayerId:'alice',round:3,maxRounds:10,players,result:null,acknowledged:false};
export const compactViews: Record<string, Record<string, unknown>> = {
 'trou-noir':{...common,kind:'trou-noir',phase:'answering',answerSeconds:30,question:{prompt:'Quel élément chimique a pour symbole Au ?',category:'sciences',difficulty:3,addresseeIsMe:true},judging:null,reveal:null,allowedActions:['SUBMIT_ANSWER','RESIGN']},
 'ttmc':{...common,kind:'ttmc',phase:'choose_level',targetScore:40,answerSeconds:30,themeSelectionSeconds:30,theme:{themeId:'t',label:'Le grand écran',description:'Des films cultes, des personnages inoubliables. Jusqu’où iras-tu ?'},chosenLevel:null,lastChanceOfRound:false,technicalReplacement:false,question:null,judging:null,reveal:null,allowedActions:['CHOOSE_LEVEL','RESIGN']},
 'skyjo':{...common,kind:'skyjo',phase:'setup',format:'short',turnSeconds:60,myGrid:Array.from({length:12},(_,slot)=>({slot,revealed:false})),opponentGrid:Array.from({length:12},(_,slot)=>slot===2||slot===5?{slot,revealed:true,value:slot===2?-2:8}:{slot,revealed:false}),held:null,discardTop:4,discardCount:1,drawCount:125,removedCount:0,revealedCount:[0,2],remainingCount:[12,12],closingSeat:null,lastTurn:false,cumulative:[0,0],roundSummary:null,allowedActions:['REVEAL_INITIAL','RESIGN']},
 'bombparty':{...common,kind:'bombparty',phase:'playing',turn:12,maxTurns:100,turnSeconds:12,initialSeconds:15,sequenceDifficulty:'normal',sequence:'TRA',lives:[3,2],scores:[7,4],timeouts:[0,0],validWordsTotal:11,acceptedWords:[{turn:10,word:'TRAVERSER',sequence:'TRA'},{turn:11,word:'CONTRASTE',sequence:'TRA'}],recentWords:[],longestWordLength:9,meanAcceptedResponseMs:null,allowedActions:['SUBMIT_WORD','RESIGN']},
 'compatibilite':{...common,kind:'compatibilite',phase:'answering',category:'amitie',questionIndex:3,questionCount:10,question:{itemId:'q',prompt:'Un week-end improvisé, vous partez où ?',options:[{id:'a',label:'À la mer, les pieds dans le sable'},{id:'b',label:'À la montagne, loin du bruit'},{id:'c',label:'Explorer une ville inconnue'},{id:'d',label:'Nulle part, on est bien ici'}]},myChoice:null,mySubmitted:false,opponentSubmitted:false,opponentChoice:null,matches:2,compared:3,skipped:0,skipsRemaining:3,sharedScore:null,allowedActions:['SUBMIT_CHOICE','SKIP_QUESTION','RESIGN']},
 'longueur-onde':{...common,kind:'longueur-onde',phase:'guessing',rounds:8,clueSeat:1,guessSeat:0,isClueGiver:false,axis:{itemId:'a',leftLabel:'Très froid',rightLabel:'Très chaud',category:'quotidien'},target:null,clue:'Un café tout juste servi',myGuess:null,total:8,lastPoints:4,lastError:2,missed:0,allowedActions:['SUBMIT_GUESS','RESIGN'],config:{rounds:8,clueSeconds:90,guessSeconds:60}},
 'bataille-navale':{...common,kind:'bataille-navale',phase:'setup',turnSeconds:null,turn:1,myFleet:[],myShots:[],incomingShots:[],myReady:false,opponentReady:false,sunkByMe:[],sunkOfMine:[],hitsByMe:0,missesByMe:0,opponentFleet:null,lastShot:null,allowedActions:['SET_FLEET','RANDOMIZE_FLEET','READY_FLEET','RESIGN']}
};

compactViews.geographie={...common,kind:'geographie',phase:'placing',rounds:5,turnSeconds:60,difficulty:'easy',selection:'random',target:{id:'paris',name:'Paris',departmentName:'Paris'},targetPoint:null,players:players.map(p=>({...p,avatarPreset:'avatar-1',submitted:false,placement:null})),challenge:null,totals:[0,0],lastRound:null};
compactViews.uno={...common,kind:'uno',phase:'playing',turns:12,turnSeconds:30,activeColor:'red',topCard:{id:'top',color:'red',symbol:'3'},drawPileCount:35,hand:Array.from({length:7},(_,i)=>({id:`c${i}`,color:['red','blue','yellow','green'][i%4],symbol:String(i)})),opponentHand:null,drawnCard:null,playableCardIds:['c0','c4'],pendingPenalty:null,players:players.map(p=>({...p,cardCount:7})),counters:{cardsPlayed:0,cardsDrawn:0,penaltyCardsTaken:0,missedAnnouncements:0,turns:12},actions:{canDraw:true,canPlay:true,canPlayDrawn:false,canKeepDrawn:false,canResign:true}};
